archivo a array
luciamar1/cub3D pull request #1
Opened 2024-01-15 17:21 UTC by luciamar1

2024-01-25 17:40 UTC, migueldar requested changes

2024-01-25 17:40 UTC, migueldar commented on cub3D
eliminalo

2024-01-25 17:40 UTC, migueldar commented on malloc_debug.sh
> +	./minishell < $3 >> log 2>> logerr
cambia ./minishell por ./cub3D

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +        return(printf("incorrect extension\n"), 0);
los errores por la salida de error (write(2...))

2024-01-25 17:40 UTC, migueldar commented on objs/main/main.o
eliminalo

2024-01-25 17:40 UTC, migueldar commented on objs/parser/parser_1.o
eliminalo

2024-01-25 17:40 UTC, migueldar commented on objs/utils/utils_1.o
eliminalo

2024-01-25 17:40 UTC, migueldar commented on src/utils/utils_1.c
> +char	*ft_strjoin_chetao(char **s1, char **s2)
no puedes poner "chetao"

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +int parser(int argc, char **argv)
entiendo que la idea es guardar todo el documento en una linea, pero creo que eso va a hacer mas dificil la validacion del mapa (y de todo lo demas) en comparacion a un array bidimensional. Porque has decidido guardar todo en una linea?

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +        return(printf("incorrect number of arguments"), 0);
error por salida de error

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +    return(1);
en los numeros usados para el return de la funcion, recuerda que el estandar es usar 0 para correcto y cualquier otro numero para incorrecto :)

2024-01-25 17:40 UTC, migueldar commented on src/utils/utils_1.c
> +	  	free(*s1);
no es una buena practica que libere memoria una funcion que no la reserva

2024-01-25 17:40 UTC, migueldar commented on src/utils/utils_1.c
> +void print_biarr(char **str)
esta funcion la usas solo para debuggear, verdad? te propongo crear src/debug donde metamos todos las funciones que usemos para debuggear y printear cosas, asi es mas facil de distinguir

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +		return (printf("the file can't be open\n"), NULL);
error por 2

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +        new_line = get_next_line(fd);
y si el gnl devuelve NULL porque se ha quedado sin memoria (ha fallado un malloc), como lo diferencias de que devuelva NULL porque ha acabado de leer? Tambien hay que plantearse si es necesario diferenciar...

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +		return (printf("the file can't be open\n"), NULL);
*opened

2024-01-25 17:40 UTC, migueldar commented on src/parser/parser_1.c
> +        line_document = ft_strjoin_chetao(&line_document, &new_line);
y si falla este malloc?

2024-01-25 17:40 UTC, migueldar commented on src/utils/utils_1.c
> +	*s = 0;
para que me vale esta linea?

2024-01-25 17:40 UTC, migueldar commented on src/main/main.c
> +#include "../../cub3d.h"
estaria guay no tener que incluirlo asi, sino solo con #include "cub3d.h", podriamos hacerlo parecido a como en la minishell

2024-01-25 17:40 UTC, migueldar commented on Makefile
> +	cc $(CFLAGS) -c src/debug/malloc_debug.c -o objs/debug/malloc_debug.o
tienes que incluir el archivo malloc_debug.c y malloc_debug.h de la minishell para que esto funcione

2024-01-25 17:40 UTC, migueldar commented on Makefile
> +.PHONY: all clean fclean re fclean_nolib re_nolib malloc_debug sanitize lucia re_lucia leaks
quita de aqui las reglas que no esten en la makefile actual

2024-01-25 18:25 UTC, luciamar1 commented on src/utils/utils_1.c
> +	*s = 0;
no te entiendo?

2024-01-25 18:26 UTC, luciamar1 commented on src/main/main.c
> +#include "../../cub3d.h"
ya pero como en la mini os arrepentimos de tener las librerias en otra carpeta he decidido dejarla fuera

2024-01-25 18:27 UTC, luciamar1 commented on cub3D
hecho

2024-01-25 18:28 UTC, luciamar1 commented on malloc_debug.sh
> +	./minishell < $3 >> log 2>> logerr
hecho

2024-01-25 18:28 UTC, luciamar1 commented on src/parser/parser_1.c
> +        return(printf("incorrect extension\n"), 0);
hecho

2024-01-25 18:28 UTC, luciamar1 commented on objs/main/main.o
hecho

2024-01-25 18:28 UTC, luciamar1 commented on objs/parser/parser_1.o
hecho

2024-01-25 18:28 UTC, luciamar1 commented on src/parser/parser_1.c
> +        line_document = ft_strjoin_chetao(&line_document, &new_line);
hecho

2024-01-25 18:36 UTC, luciamar1 commented on Makefile
> +	cc $(CFLAGS) -c src/debug/malloc_debug.c -o objs/debug/malloc_debug.o
hecho

2024-01-25 19:21 UTC, migueldar requested changes

2024-01-25 19:21 UTC, migueldar commented on src/main/main.c
> +#include "../../cub3d.h"
esta bien dejarla fuera (aunque yo al menos la meteria en sources) pero aun asi, puedes conseguir que se pueda incluir solo con #include "cub3d.h" con la flag -I en el gcc (como en la mini)

2024-01-25 19:21 UTC, migueldar commented on src/utils/utils_1.c
> +	*s = 0;
que que hace esa linea (*s = 0;)

2024-01-26 12:42 UTC, luciamar1 commented on src/utils/utils_1.c
> +	*s = 0;
para limitar el array con un '\0' ten en cuenta que uso malloc no calloc

2024-01-26 12:48 UTC, luciamar1 commented on src/utils/utils_1.c
> +	*s = 0;
lo cambio a '\0' para que se entienda mejor

2024-01-26 12:53 UTC, luciamar1 commented on src/main/main.c
> +#include "../../cub3d.h"
luego hablamos de este tema

2024-02-12 17:10 UTC, closed without merging